### ISSUE TITLE
New version for Phython 3

### ISSUE THREAD

**Issue by mbrasse** [ashleycoxley/twitter-analytics-export#2]
Hi Ashley, 
Playing around with your script I got it working - it is great and will help me a lot because I want to build a dashboard which downloads the data regularly. To use Phython 3 (3.5.1 on win32) required a few changes. Also under Windows (7) I had issues with the splitting and encoding. So I simplified it quite a bit and the result now looks exactly the same, as when clicking the <Export> button on the Twitter frontend. 

But as I am not very familiar with Phython, I would be very happy, if you could look through and see if I took any shortcut which is harmful (e.g. when working on other OS). 

Thanks and best regards
         Micha

`import requests
import re
import time
import json
import datetime
import urllib
import io
import codecs
import csv
import argparse
import os

def twitter_flow(USERNAME, PASSWORD, ANALYTICS_ACCOUNT, NUM_DAYS, OUTPUT_DIRECTORY):
    user_agent = {'User-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'}
    session = twitter_login(USERNAME, PASSWORD, user_agent)
    start_time, end_time = get_date_range(NUM_DAYS)
    data_string = get_tweet_data(session, ANALYTICS_ACCOUNT, start_time, end_time, user_agent)

```
outfile = get_filename(OUTPUT_DIRECTORY, start_time, end_time)

f = open(outfile, 'w')
f.write(data_string)

print ("CSV downloaded: ", outfile)
```

def twitter_login(user, pw, user_agent):
    """Start a requests session and login to Twitter with credentials.
    Returned object is logged-in session."""

```
tw_url = "https://twitter.com/"
session = requests.session()
first_req = session.get(tw_url)

auth_token_str = re.search(r'<input type="hidden" name="authenticity_token" value="([a-zA-Z0-9]*)"\>',
      first_req.text)
authenticity_token = auth_token_str.group(1)

login_url = 'https://twitter.com/sessions'

payload = {
    'session[username_or_email]' : user,
    'session[password]' : pw,
    'remember_me' : '1',
    'return_to_ssl' : 'true',
    'scribe_log' : None,
    'redirect_after_login':'/',
    'authenticity_token': authenticity_token
}

login_req = session.post(login_url, data=payload, headers=user_agent)
return session
```

def get_date_range(num_days):
    """Return date strings in UTC format. The data is returned as 
    (start, end)
    with the end date being today and the begin date being 'num_days' prior.
    Twitter's maximum total days is 90."""

```
today = datetime.datetime.utcnow()
prior = today - datetime.timedelta(days=num_days)

def add_milliseconds(timestamp): # arbitrary since millisecond precision not necessary
    milli_ts = int(time.mktime(timestamp.timetuple()) * 1000)
    milli_ts = str(milli_ts)
    return milli_ts

start = add_milliseconds(prior)
end = add_milliseconds(today)

return (start, end)
```

def get_tweet_data(session, analytics_account, start_time, end_time, user_agent):
    """Complete the process behind clicking 'Export data' at 
    https://analytics.twitter.com/user/USERNAME/tweets
    Data is returned as a raw string containing comma-separated data"""

```
export_url = "https://analytics.twitter.com/user/" + analytics_account + "/tweets/export.json"
bundle_url = "https://analytics.twitter.com/user/" + analytics_account + "/tweets/bundle"

export_data = {
    'start_time' : end_time,
    'end_time' : start_time,
    'lang' : 'en'
}
querystring = '?' + urllib.parse.urlencode(export_data)

status = 'Pending'
counter = 0
while status == 'Pending':
    attempt = session.post(export_url + querystring, headers=user_agent)
    print (export_url + querystring, counter, status)
    status_dict = json.loads(attempt.text)
    status = status_dict['status']
    counter += 1
    time.sleep(5)

csv_header = {'Content-Type': 'application/csv',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
          'Accept-Encoding': 'gzip, deflate, sdch',
          'Accept-Language': 'en-US,en;q=0.8',
          'Upgrade-Insecure-Requests': '1',
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'}

data_req = session.get(bundle_url + querystring, headers=csv_header)
print ("data_req response: ", data_req.status_code)
return data_req.text
```

def get_filename(output_dir, start_time, end_time):
    """Build descriptive filename for CSV"""
    f_name = 'twitter_data_' + start_time + '_' + end_time + '.csv'
    full_path = output_dir + '/' + f_name

```
return full_path
```

if **name** == '**main**':
    parser = argparse.ArgumentParser()
    parser.add_argument('-u', help="Twitter handle for login", required=True)
    parser.add_argument('-p', help="Password", required=True)
    parser.add_argument('-d', help="Number of previous days' data to return (max: 90)", type=int, default=60)
    parser.add_argument('-o', help="Output directory", default=os.getcwd())
    parser.add_argument('-a', help="Account to return data for (default: -u)", required=False)
    args = parser.parse_args()

```
USERNAME = args.u    
PASSWORD = args.p
if args.a is not None: # default account for analytics is login account
    ANALYTICS_ACCOUNT = args.a
else:
    ANALYTICS_ACCOUNT = USERNAME
NUM_DAYS = args.d
OUTPUT_DIRECTORY = args.o

twitter_flow(USERNAME, PASSWORD, ANALYTICS_ACCOUNT, NUM_DAYS, OUTPUT_DIRECTORY)
```

`

**Comment by t-pfaff** [comment]
@mbrasse Check out my [Python3 port of the script](https://github.com/t-pfaff/twitter-analytics-export). However, it seems that Twitter is blocking the script now.

**Comment by philippe2803** [comment]
In case your script remains blocked, I just wrote a Python alternative that uses Selenium with chromedriver: https://github.com/philippe2803/twitter-analytics-wrapper
